#!/bin/bash

set -euo pipefail

declare -ri length=${1:-3}

function separate() {
  awk NF=NF FPAT=. OFS="\n"
}

# Separate the characters with newlines
CHARACTERS=$(echo '~!@#$%^&*()_+=-`{}[]|\:";<>,.?/' | separate)

function password() {
  (
    shuf -n"$length" /usr/share/dict/words;       # take n random words
    # generate a random string
    (grep -Eoa --max-count 1 '[A-Za-z0-9]{3,4}' < /dev/random | head -n1 ) ;
    shuf -n1 <<< "$CHARACTERS";
  ) | shuf |
    tr '\n' ' ' |               # replace newlines with spaces
    sed -r "s/'//g" |           # remove quotes, they're bothersome
    sed -r 's/ $//'             # remove trailing space
}

password; echo
